# This is a basic workflow to help you get started with Actions
name: CI
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      
    - name: Setup Webpack and React
      run: |
        npm install --save-dev webpack 
        npm install -D webpack-cli
        npm install uglifyjs-webpack-plugin --save-dev
        npm install --save-dev babel-core babel-preset-es2015 babel-preset-react
        npm install babel-loader@^7 --save-dev
        npm i react react-dom --save-dev
        npm install --save react-router-dom history
        
    # Runs a set of commands using the runners shell
    - name: npm run build
      run: npm run build --prefix templates/static/
        
    - uses: actions/upload-artifact@v2
      with:
        name: bundle.js.map
        path: templates/public/bundle.js.map

    - uses: actions/upload-artifact@v2
      with:
        name: bundle.js
        path: templates/public/bundle.js

  deploy:
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
    - uses: actions/checkout@v2
      
    - uses: actions/download-artifact@v2
      with:
        name: bundle.js.map

    - name: Rollbar deploy
      uses: mrunalk/github-deploy-action@1.1.4
      with:
        # Environment where your code is running. e.g. production
        environment: production
        # Version deployed
        version: ${{ github.sha }}
        # Deploy status
        status: succeeded # optional, default is succeeded
        source_map: "bundle.js.map bundle.js"
        minified_url: 127.0.0.1:5000/public/bundle.js
      env:
          ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_ACCESS_TOKEN }}
